Traceback (most recent call last):
  File "/media/kingston_shared/thesis/sss/train_fixed.py", line 273, in <module>
    losses = estimate_loss()
  File "/home/ronald/miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/kingston_shared/thesis/sss/train_fixed.py", line 230, in estimate_loss
    logits, loss = model(X, Y)
  File "/home/ronald/miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ronald/miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ronald/miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/ronald/miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ronald/miniconda3/envs/torchenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/kingston_shared/thesis/sss/model_fixed2.py", line 531, in forward
    assert t <= self.config.block_size, f"Cannot forward sequence of length {t}, block size is only {self.config.block_size}"
AssertionError: Cannot forward sequence of length 512, block size is only 256